### ISSUE TITLE
Jura Z6 support

### ISSUE THREAD

**Issue by cor73x** [AlexxIT/Jura#12]
I have Jura Z6 with Bluetooth, it is visible in JOE app, also mac address was visible when I was adding integration but integration is unable to get details from coffee machine. 

I suspect that this may be due older hardware? I'm using esp32 with proxy enabled, I have moved it closer to coffee machine but this didn't help. 
How can I help you debug this and make it supported? 

When I'm reloading integration in HA log I see few errors about config entries. 

```
023-12-31 10:43:40.953 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry  for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 557, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 176, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 203, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-12-31 10:43:40.956 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry  for button
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 557, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 73, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 203, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-12-31 10:43:40.960 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry  for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 557, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 120, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 203, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-12-31 10:43:40.964 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry  for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 557, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 118, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 203, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

**Comment by AlexxIT** [comment]
Yes. This error probably because your BT don't support connect mode. I'll fix error on integration restart. But you needs to change BT adapter.

**Comment by cor73x** [comment]
ok, but it is same blue smart connect dongle: https://uk.jura.com/en/homeproducts/accessories/SmartConnect-Main-72167 it says that it is compatible with ENA8, E8 (same as in README as supported) and Z6. 
I checked in JOE app and it says firmware 05.08 (latest). If you can guide me I can try to debug/help fixing.

**Comment by AlexxIT** [comment]
I think this issue can be closed
