### ISSUE TITLE
Numeric values lost after upgrade to HA2024.1.0

### ISSUE THREAD

**Issue by Avatar1976** [AlexxIT/Jura#14]
![Screenshot_20240104_131657_Home Assistant](https://github.com/AlexxIT/Jura/assets/47725430/2163c45d-52f6-4699-bdf5-fad03e10ac26)
I also noted an error when selecting products about not being able to select "none". Suspect related to numeric values.

**Comment by Avatar1976** [comment]
Further Info I get the following three errors on start.
`Logger: homeassistant.components.bluetooth.manager
Source: components/bluetooth/manager.py:109
Integration: Bluetooth (documentation, issues)
First occurred: 07:27:15 (1 occurrences)
Last logged: 07:27:15

Error in bluetooth callback
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/manager.py", line 109, in _discover_service_info
    callback(service_info, BluetoothChange.ADVERTISEMENT)
  File "/config/custom_components/jura/__init__.py", line 23, in update_ble
    devices[entry.entry_id] = Device(
                              ^^^^^^^
  File "/config/custom_components/jura/core/device.py", line 52, in __init__
    machine = get_machine(number)
              ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jura/core/device.py", line 207, in get_machine
    with f.open("machinefiles/" + items[2] + ".xml") as xml:
                ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'items' where it is not associated with a value
`
`Logger: homeassistant.components.number
Source: helpers/entity_platform.py:507
Integration: Number (documentation, issues)
First occurred: 07:27:20 (1 occurrences)
Last logged: 07:27:20

Error adding entities for domain number with platform jura
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 246, in capability_attributes
    ATTR_STEP: self._calculate_step(min_value, max_value),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 329, in _calculate_step
    value_range = abs(max_value - min_value)
                      ~~~~~~~~~~^~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
`
`Logger: homeassistant.components.number
Source: helpers/entity_platform.py:507
Integration: Number (documentation, issues)
First occurred: 07:27:20 (1 occurrences)
Last logged: 07:27:20

Error adding entities for domain number with platform jura
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 246, in capability_attributes
    ATTR_STEP: self._calculate_step(min_value, max_value),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 329, in _calculate_step
    value_range = abs(max_value - min_value)
                      ~~~~~~~~~~^~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
`
Hope something helps here should I try delete my config and rediscover machine?

**Comment by Avatar1976** [comment]
Updating to the newest HA2024.1.1 still resulted in the same, + I tried deleting config and rediscovering it. Resulted in the numeric free text entry fields disappearing completely.
![Screenshot_20240106_075930_Home Assistant](https://github.com/AlexxIT/Jura/assets/47725430/6318083c-a2b8-4f3b-95b8-57824350f4e2)

**Comment by Avatar1976** [comment]
Is there any diagnostic / troubleshooting data that would help here?

**Comment by AlexxIT** [comment]
No. I just have a lot of projects. Most of them broken by 2024.1. Needs some time to fix them one by one

**Comment by mrjjr1980** [comment]
> No. I just have a lot of projects. Most of them broken by 2024.1. Needs some time to fix them one by one

Thanks for your effort, I will wait patiently.

**Comment by Avatar1976** [comment]
> No. I just have a lot of projects. Most of them broken by 2024.1. Needs some time to fix them one by one

No problem, any way the community can help just ask.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/Jura/releases/tag/v1.0.3

**Comment by Avatar1976** [comment]
Got it thanks AlexIT! Working well 😊
