### ISSUE TITLE
Bug: cannot access local variable 'items' 

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/Jura#23]
```
Logger: homeassistant.components.bluetooth.manager
Source: components/bluetooth/manager.py:109
Integration: Bluetooth (documentation, issues)
First occurred: 06:36:39 (1 occurrences)
Last logged: 06:36:39

Error in bluetooth callback
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/manager.py", line 109, in _discover_service_info
    callback(service_info, BluetoothChange.ADVERTISEMENT)
  File "/config/custom_components/jura/__init__.py", line 23, in update_ble
    devices[entry.entry_id] = Device(
                              ^^^^^^^
  File "/config/custom_components/jura/core/device.py", line 52, in __init__
    machine = get_machine(number)
              ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jura/core/device.py", line 207, in get_machine
    with f.open("machinefiles/" + items[2] + ".xml") as xml:
                                  ^^^^^
UnboundLocalError: cannot access local variable 'items' where it is not associated with a value
```

**Comment by MikeBP13** [comment]
I'm having the same issue.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/Jura/releases/tag/v1.1.0
