### ISSUE TITLE
strange behaviour after enabling the custom component

### ISSUE THREAD

**Issue by remb0** [AlexxIT/Jura#5]
I bought the bluetooth module instead of the wifi and saw an MAC adres..
After choosing the mac adres:  An device with 9 entities is made. But whitin a minute all entities got an red exclamation mark, and are not available.

I have enabled a fed esp32 boards with esphome as proxies. 

but my system become slow and almost onresponsible.   the only thing I found in the logs:

```
Logger: homeassistant.components.bluetooth.manager
Source: custom_components/jura/core/device.py:42
Integration: Bluetooth (documentation, issues)
First occurred: 16:39:35 (1 occurrences)
Last logged: 16:39:35

Error in bluetooth callback
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/manager.py", line 664, in async_register_callback
    callback(service_info, BluetoothChange.ADVERTISEMENT)
  File "/config/custom_components/jura/__init__.py", line 23, in update_ble
    devices[entry.entry_id] = Device(
                              ^^^^^^^
  File "/config/custom_components/jura/core/device.py", line 42, in __init__
    manufacturer = advertisment.manufacturer_data[171]
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 171
```

**Comment by AlexxIT** [comment]
Try master version. Should be fixed there

**Comment by AlexxIT** [comment]
Should be fixed https://github.com/AlexxIT/Jura/releases/tag/v1.0.1
